- hosts: all  # Target all hosts in your inventory
  vars:
    namespace: null
    vmname: null
    password: null
    instancetype: u1.medium
    ssh_public_key: null
    vm_image: null
  tasks:
  - name: Create project
    redhat.openshift.k8s:
      state: present
      definition:
        apiVersion: project.openshift.io/v1
        kind: Project
        metadata:
          name: "{{ namespace }}"
  - name: Create fedora virtual machine
    redhat.openshift_virtualization.kubevirt_vm:
      state: present
      name: "{{ vmname }}"
      namespace: "{{ namespace }}"
      labels:
        app: httpd
      instancetype:
        name: "{{ instancetype }}"
      preference:
        name: fedora
      spec:
        domain:
          devices:
            interfaces:
              - name: default
                masquerade: {}
        networks:
          - name: default
            pod: {}
        volumes:
          - containerDisk:
              image: '{{ vm_image }}'
            name: containerdisk
          - cloudInitNoCloud:
              userData: |-
                #cloud-config
                user: fedora
                password: "{{ password }}"
                chpasswd: { expire: False }
                ssh_authorized_keys:
                - "{{ ssh_public_key }}"
            name: cloudinit
  
  - name: Wait for virtual machine IP to be populated
    kubernetes.core.k8s_info:
      api_version: kubevirt.io/v1
      kind: VirtualMachineInstance
      name: "{{ vmname }}"
      namespace: "{{ namespace }}"
    register: vmi
    retries: 60
    delay: 10
    until: (vmi.resources[0].status.interfaces[0]['ipAddress'] | default('')) | length > 0
