- hosts: all  # Target all hosts in your inventory
  vars:
    namespace: workloads
    vmname: fedora
    password: password
    storage_size: 30Gi
    storageclass_name: netapp
    instancetype: u1.medium

  tasks:
  - name: Create project
    redhat.openshift.k8s:
      state: present
      definition:
        apiVersion: project.openshift.io/v1
        kind: Project
        metadata:
          name: "{{ namespace }}"

  - name: Create fedora virtual machine
    redhat.openshift_virtualization.kubevirt_vm:
      state: present
      name: "{{ vmname }}"
      namespace: "{{ namespace }}"
      labels:
        app: httpd
      instancetype:
        name: "{{ instancetype }}"
      preference:
        name: fedora
      data_volume_templates:
        - metadata:
           name: "{{ vmname }}-rootdisk"
          spec:
            sourceRef:
              kind: DataSource
              name: fedora
              namespace: openshift-virtualization-os-images
            storage:
              accessModes:
                - ReadWriteMany
              resources:
                requests:
                  storage: "{{ storage_size }}"
              storageClassName: "{{ storageclass_name }}"
      spec:
        domain:
          devices:
            interfaces:
              - name: default
                masquerade: {}
            disks:
              - disk:
                  bus: virtio
                name: rootdisk
              - disk:
                  bus: virtio
                name: cloudinit
        networks:
          - name: default
            pod: {}
        volumes:
          - dataVolume:
              name: "{{ vmname }}-rootdisk"
            name: rootdisk
          - cloudInitNoCloud:
              userData: |-
                #cloud-config
                user: fedora
                password: "{{ password }}"
                chpasswd: { expire: False }
                ssh_authorized_keys:
                - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvlKyJ1gK8v4YGl12hmz1Mq1QnA0FHnMgFD6dA0K/dKYM0uBlg/XtNH9G9xtoK7ifM1rK43pi0P7iQ7r9QNQIlggztrsYPMMjtGXt5R4Z8B5jWNIjQn4rAMghZbck016PJQ6P3R4787MXuZi339F/lP6FvA81el4Fm4aIVv5bbWyYWMjQ2aQDQb2zGh/GWYervcmV3+jjTK5MQzLOd70W5OIggicafze0dIWbLay9ks+5fGqX7klre8ZhOFWME806gJPoBjtfteD9RQ9Fgxio01gf8FuJSfhsuSz831nVmx7A6jjTGa3ExnVB1SCERyJoC5DjLeU4XmOAOozSfYYypnMHYoBhVvWGpYzHFEauUlekzJ30WBnMTXMqU7tg6LuQtL7RG329VCDvNy3/aHhb4NM4n79TB1v+s49yP6XxciuHeHK5VgqIG3D72LFS2+EM7bO8Y9onqgIXWB/DOh4mKroKBE8o3Tb9sPhX3C8xLZGkebTGW8kbcwIvd4pXUHVk= nos@tanzu-step
            name: cloudinit
  
  - name: Wait for virtual machine IP to be populated
    kubernetes.core.k8s_info:
      api_version: kubevirt.io/v1
      kind: VirtualMachineInstance
      name: "{{ vmname }}"
      namespace: "{{ namespace }}"
    register: vmi
    retries: 60
    delay: 10
    until: (vmi.resources[0].status.interfaces[0]['ipAddress'] | default('')) | length > 0
