- hosts: all  # Target all hosts in your inventory
  vars:
    namespace: workloads
    vmname: fedora
    password: Passw0rd!
    storage_size: 30Gi
    storageclass_name: netapp
    instancetype: u1.medium

  tasks:
  - name: Create a random_password 12-character string and format it
    set_fact:
      random_password: "{{ lookup('ansible.builtin.password', '/dev/null chars=ascii_letters,digits length=12') | regex_replace('(.{4})(.{4})(.{4})', '\\1-\\2-\\3') }}"

  - name: Display the random_password
    debug:
      msg: "Generated password is: {{ random_password }}"

  - name: Create project
    redhat.openshift.k8s:
      state: present
      definition:
        apiVersion: project.openshift.io/v1
        kind: Project
        metadata:
          name: "{{ namespace }}"

  - name: Create fedora virtual machine
    redhat.openshift_virtualization.kubevirt_vm:
      state: present
      name: "{{ vmname }}"
      namespace: "{{ namespace }}"
      labels:
        app: httpd
      instancetype:
        name: "{{ instancetype }}"
      preference:
        name: fedora
      data_volume_templates:
        - metadata:
            name: "{{ vmname }}-rootdisk"
          spec:
            sourceRef:
              kind: DataSource
              name: fedora
              namespace: openshift-virtualization-os-images
            storage:
              accessModes:
                - ReadWriteMany
              resources:
                requests:
                  storage: "{{ storage_size }}"
              storageClassName: "{{ storageclass_name }}"
      spec:
        domain:
          devices:
            interfaces:
              - name: default
                masquerade: {}
            disks:
              - disk:
                  bus: virtio
                name: rootdisk
              - disk:
                  bus: virtio
                name: cloudinit
        networks:
          - name: default
            pod: {}
        volumes:
          - dataVolume:
              name: "{{ vmname }}-rootdisk"
            name: rootdisk
          - cloudInitNoCloud:
              userData: |-
                #cloud-config
                user: fedora
                password: "{{ random_password }}"
                chpasswd: { expire: False }
                ssh_authorized_keys:
                - "{{ ssh_public_key }}"
            name: cloudinit

  - name: Wait for virtual machine IP to be populated
    kubernetes.core.k8s_info:
      api_version: kubevirt.io/v1
      kind: VirtualMachineInstance
      name: "{{ vmname }}"
      namespace: "{{ namespace }}"
    register: vmi
    retries: 60
    delay: 10
    until: (vmi.resources[0].status.interfaces[0]['ipAddress'] | default('')) | length > 0
